daemon:
  listen: 0.0.0.0
  port: 9876
  base_url: "/api/v0"

faster_whisper:
  model_cache_dir: /home/dwemer/remote-faster-whisper/models/
  model: bzikst/faster-whisper-large-v3-russian
  device: cuda
  device_id: 0
  compute_type: float16
  beam_size: 5
  translate: no
  language: ru
  lexicon_file: /home/dwemer/remote-faster-whisper/tes_lexicon_full_ru.txt
  hotwords: "Скайрим, Довакин, Тамриэль, Вайтран, Рифтен, Солитьюд, Виндхельм, Маркарт, Фолкрит, Данстар, Морфал, Винтерхолд, Ривервуд, Айварстед, Балгруф, Ульфрик, Туллий, Фаренгар, Лидия, Эйла, Фаркас, Вилкас, Кодлак, Дельфина, Эсберн, Серана, Бриньольф, Карлия, Цицерон, Астрид, Дж'зарго, Толфдир, Анкано, Хеймскр, Назим, Адрианна, Алвор, Хадвар, Ралоф, Гердур, Сигрид, Камилла, Алдуин, Партурнакс, Одавинг, Йоррваскр, Драконий Предел, Высокий Хротгар, Совнгард, Саартал, септимы, ярл, хускарл, тан, драугр, двемер, данмер, альтмер, босмер, каджит, аргонианин, редгард, бретонец, норд, орк, фалмер, Седобородые, Соратники, Тёмное Братство, Гильдия воров, Коллегия Винтерхолда, Талмор, Братья Бури, Обливион, даэдра, Шеогорат, Азура"

transformations:
  - ["[СЗс]\\s?[ао]вн[ао]?\\s?гард", "Совнгард"]
  - ["[Дд]ов[аы]кин", "Довакин"]
  - ["[Вв]ай[тд]ран", "Вайтран"]
